export const ADDTODO = 'addTodo'
export const DELTODO = 'delTodo'
export const TABCHANGE = 'tabChange'
export const HANDLETOGGLE = 'handleToggle'
export const CHOOSETOGGLE = 'chooseToggle'
export const DELCHECKED = 'delChecked'
